spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100KB
      max-request-size: 1MB
  datasource:
    url: jdbc:postgresql://localhost/wl
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.yandex.ru
    username: pochta@yandex.ru
    password: password
    port: 465
    protocol: smtps
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
server:
  port: 8081
mail:
  debug: true
recaptcha:
  secret: recaptcha-secret
  captcha-url: "https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s"
jwt:
  token:
    secret: jwtthewatchlist
    expired: 2592000000
file:
  logo-dir: /images/logo/