spring:

  datasource:
    url: jdbc:postgresql://localhost/wl
    username: postgres
    password: postgres

  jpa:

    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#    hibernate:
#      ddl-auto: create
  mail:
    host: smtp.yandex.ru
    username: Andersen1313@yandex.ru
    password: 1qaz!QAZXC
    port: 465
    protocol: smtps

  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

server:
  port: 8081

mail:
  debug: true

recaptcha:
  secret: 6Ldbo7kUAAAAAI6ZcMO55EjqnGy76IPDExpg0-tE
  captcha-url: "https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s"

jwt:
  token:
    secret: jwtthewatchlist
    expired: 2592000000